# Generated by Django 5.2.2 on 2026-03-09 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songuser',
            name='played_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
